### PR TITLE
Fix IE with JS since object keys must be defined but only in IE

### LINKED ISSUE #337: IE tries to download json response
I am a user who translated your project into Korean, and recently visitors have heard the same problem. The test showed me the same problem. The same issue occurred with mobile chrome.

https://github.com/dwyl/learn-to-send-email-via-google-script-html-no-server/commit/798d9c5439454050140359eb81c4bef17a6dcec0

It seems to be a problem after this commit.

I deleted line "honeypot" in line 52 of form-submission-handler.js and noticed it works again.
return {data: formData, honeypot}; ->
return {data: formData};

Perhaps you need to use an array or add a key.

### PR DESCRIPTION
**Pull request by mckennapsean**
Fixes #337 - thanks, @SaintSilver !

### CODE REVIEW

File: form-submission-handler.js [hunk 1]
```diff
@@ -49,7 +49,7 @@
       = form.dataset.email || ""; // no email by default
 
     console.log(formData);
-    return {data: formData, honeypot};
+    return {data: formData, honeypot: honeypot};
```
Comment (nelsonic) [inline form-submission-handler.js]: indeed. ES6 creeping in causing havoc in older browsers ...
